spring:
  application:
    name: clarium-sso

  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: 215b5640-18a9-4579-85f0-dee13df57b61
            client-secret: tuz8Q~Zda7W6IEDsnrucsYvol4QecDkM7J68lbu~
            scope:
              - openid
              - profile
              - email
              - https://graph.microsoft.com/User.Read
              - https://graph.microsoft.com/User.ReadBasic.All
            redirect-uri: http://localhost:8080/login/oauth2/code/
            client-name: Azure AD
        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/3dbd7e58-e2ea-40b8-bb5a-3ea2038c9535/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/3dbd7e58-e2ea-40b8-bb5a-3ea2038c9535/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            jwk-set-uri: https://login.microsoftonline.com/3dbd7e58-e2ea-40b8-bb5a-3ea2038c9535/discovery/v2.0/keys
            user-name-attribute: sub
            issuer-uri: https://login.microsoftonline.com/3dbd7e58-e2ea-40b8-bb5a-3ea2038c9535/v2.0

  datasource:
    url: jdbc:sqlserver://10.2.1.4:52752;databaseName=employee-details;encrypt=false
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  jwt:
    secret: ${JWT_SECRET}

cors:
  allowed-origins: http://localhost:4200
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true